name: Release Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.87.0
      
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      
      - name: Run tests
        run: cargo test --all-features

  build:
    name: Build on ${{ matrix.os }}
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: target/release/archerdndsys
            asset_name: archerdndsys-linux-amd64
          - os: macos-latest
            artifact_name: target/release/archerdndsys
            asset_name: archerdndsys-macos-amd64
          - os: windows-latest
            artifact_name: target/release/archerdndsys.exe
            asset_name: archerdndsys-windows-amd64.exe
            
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.87.0
      
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      
      - name: Build release binary
        run: cargo build --release
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.artifact_name }}
          if-no-files-found: error

  check_release_status:
    name: Check Release Status
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check successful build status
        run: echo "Build and test completed successfully on all platforms. Release is ready."